name: Reusable Workflow

on:
  workflow_call:

jobs:
  echo-datetime:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout caller repository
        uses: actions/checkout@v4

      - name: Call composite action
        uses: quentinadam/test3@${{ github.action_ref }}
